on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Run Super Linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Super Linter needs full git history for file changes

      - name: Run Super Linter
        uses: super-linter/super-linter@v7.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for reporting status to GitHub
          DISABLE_CHECKOV: true  # Disable Checkov linter
          DISABLE_HTML_PRETTIER: true  # Disable Prettier for HTML files
          DISABLE_JSON_PRETTIER: true  # Disable Prettier for JSON files

  build:
    runs-on: ubuntu-latest
    needs: linter  # Ensure build runs after the linter job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build the index.html file
        run: python build.py

      - name: Upload files to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after the build job
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
